### ISSUE TITLE
changing `n_topic_truncate` also changes the number of live and dead topics returned, not sure why

### ISSUE THREAD

**Issue by bmill3r** [chyikwei/bnp#14]
Hello,

This question my be a result of my lack of understanding, but I have noticed that changing the parameter `n_topic_truncate`, which controls the total number of topics returned, also changes the number of live and dead topics predicted by the model. For example, if I choose `n_topic_truncate = 200`, it may return 200 topics where 10 have 'useful information' and the 190 do not. What I mean is the 10 topics will make up over 99% of the corpus, and all have unique distributions of topic-words. But the remaining 190 topics will all have identical topic-word distributions and make up a small fraction of the corpus. 

Now, if I change `n_topic_truncate = 20`, instead of obtaining 10 live topics and 10 dead topics, the model may return, for example, 3 live topics and 17 dead ones. Why is this? Why are the same 10 live topics not identified with different `n_topic_truncate` values? I can understand that if `n_topic_truncate` is too small, then the model may contain too few topics to represent the corpus. But I have found that even `n_topic_truncate=2` returns one topic that represents the majority of the data and the second topic hardly presents any (based on `hdp.topic_distribution()`). 

Conversely, increasing `n_topic_truncate` seems to always increase the number of live topics. Then, how does one determine an appropriate value for `n_topic_truncate`? In this way, this HDP seems like LDA, in which one needs to designate K beforehand. Am I missing something?

Thanks for your time and I appreciate any help or insight.

**Comment by chyikwei** [comment]
Hi,
ASFAIK there is no best way to decide number of topics. HDP just assume the topics are infinite with DP prior (instead of a fix number K) so there is no guarantee it will find the right number of topics for you or the topics you see are consistent across different setting. 

In practice, my personal experience is: 
1) when you increase `n_topic_truncate`, a topic will be split to multiple smaller and similar topics. (This is the same as LDA.)
2) how you initialize the stick break process also plays an important role on number of topics. You can try beta distribution which I commented out before. (https://github.com/chyikwei/bnp/blob/master/bnp/online_hdp.py#L439-L449)

And for `n_topic_truncate=2` case, I tested it with dummy data and the result looks ok (I got 48%, 52% for topic proportion). You might need to turn hyper-parameters for your dataset.
```python
>>> tf = make_doc_word_matrix(n_topics=5,
                              words_per_topic=10,
                              docs_per_topic=100,
                              words_per_doc=20,
                              shuffle=True,
                              random_state=0)

>>> hdp = HierarchicalDirichletProcess(n_topic_truncate=2, n_doc_truncate=3, max_iter=5, random_state=0)
>>> hdp.fit(tf)
HierarchicalDirichletProcess(alpha=1.0, batch_size=256, burn_in_iters=3,
               check_doc_likelihood=False, eta=0.01, evaluate_every=0,
               kappa=0.5, learning_method='online',
               max_doc_update_iter=100, max_iter=5, mean_change_tol=0.001,
               n_doc_truncate=3, n_jobs=1, n_topic_truncate=2, omega=1.0,
               perp_tol=0.1, random_state=0, scale=1.0, tau=10.0,
               total_samples=1000000, verbose=0)
>>> print_top_words(hdp, 10)
Topic 0 (proportion: 0.48): 3 1 7 5 19 10 4 8 0 2
Topic 1 (proportion: 0.52): 48 46 35 31 39 42 30 16 33 45
```

**Comment by bmill3r** [comment]
Thank you so much for your response. That helps a lot!
